export const LOGIN_CONFIG = {
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  COACH_LOGIN: "COACH_LOGIN",
  COACH_SIGNUP: "COACH_SIGNUP",
  ADMIN: "ADMIN",
};

export const ROLE_CONFIG = {
  CLIENT: "ROLE_CLIENT",
  COACH: "ROLE_COACH",
  ADMIN: "ROLE_ADMIN",
};
